--- BISOGNA METTERE GLI ATTRIBUTI CHE SONO ID (ci servono per il join), GLI ATTRIBUTI CHE COMPAIONO NELLA VISTA MATERIALIZZATA E QUELLI CHE SONO NEL TRIGGER

--- LOG su INCASSO
CREATE MATERIALIZED VIEW LOG ON INCASSO
WITH SEQUENCE, ROWID
(IdSede, IdServizio, IdCategoriaAzienda, IdTempo, #consulenze, incasso)
INCLUDING NEW VALUES;

--- LOG su SERVIZIO
CREATE MATERIALIZED VIEW LOG ON SERVIZIO
WITH SEQUENCE, ROWID
(IdServizio, Servizio, TipologiaServizio)
INCLUDING NEW VALUES;

--- LOG su TEMPO
CREATE MATERIALIZED VIEW LOG ON TEMPO
WITH SEQUENCE, ROWID
(IdTempo, Semestre, Anno)
INCLUDING NEW VALUES;

--- LOG su SEDECONSULENTI
CREATE MATERIALIZED VIEW LOG ON SEDECONSULENTI
WITH SEQUENCE, ROWID
(IdSede, Regione)
INCLUDING NEW VALUES;

--- LOG su AZIENDA
CREATE MATERIALIZED VIEW LOG ON AZIENDA
WITH SEQUENCE, ROWID
(IdCategoriaAzienda, Nazionalità)
INCLUDING NEW VALUES;