/*QUERY 1*/
SELECT DATEYEAR, PHONERATETYPE, SUM(PRICE) AS RedditoAnnuoTariffa,
    SUM(SUM(PRICE)) OVER(PARTITION BY PHONERATETYPE) AS ReddittoTariffa,
    SUM(SUM(PRICE)) OVER(PARTITION BY DATEYEAR) AS ReddittoAnnuo,
    SUM(SUM(PRICE)) OVER() AS RedditoTotale
FROM PHONERATE P, FACTS F, TIMEDIM T
WHERE F.ID_TIME = T.ID_TIME
    AND F.ID_PHONERATE = P.ID_PHONERATE
GROUP BY DATEYEAR, PHONERATETYPE
ORDER BY DATEYEAR, PHONERATETYPE;

/*QUERY 2*/
SELECT DATEMONTH, SUM(NUMBEROFCALLS) AS NumeroMensileChiamate, SUM(PRICE) AS RedditoMensile, 
    RANK() OVER (ORDER BY SUM(PRICE) DESC) AS RankReddito
FROM TIMEDIM T, FACTS F
WHERE T.ID_TIME = F.ID_TIME
GROUP BY DATEMONTH;

/*QUERY 3*/
SELECT DATEMONTH, SUM(NUMBEROFCALLS) AS NumTotaleChiamate,
    RANK() OVER(ORDER BY SUM(NUMBEROFCALLS) DESC) AS RankTotaleChiamate
FROM TIMEDIM T, FACTS F
WHERE T.ID_TIME = F.ID_TIME
    AND DATEYEAR = '2003'
GROUP BY DATEMONTH;

/*QUERY 4*/
SELECT DAYDATE, SUM(PRICE) AS RedditoTotale,
    AVG(SUM(PRICE)) OVER (ORDER BY DAYDATE
    	RANGE BETWEEN INTERVAL '2' DAY PRECEDING AND CURRENT ROW) AS MovingAvgReddito
FROM TIMEDIM T, FACTS F
WHERE T.ID_TIME = F.ID_TIME
    AND DATEMONTH = '7-2003'
GROUP BY DAYDATE;

/* QUERY 5*/
SELECT DATEMONTH, DATEYEAR, SUM(PRICE) AS RedditoMensile,
    SUM(SUM(PRICE)) OVER (PARTITION BY DATEYEAR
    ORDER BY DATEYEAR, DATEMONTH) AS RedditoCumulativo
FROM TIMEDIM T, FACTS F
WHERE T.ID_TIME = F.ID_TIME
GROUP BY DATEMONTH, DATEYEAR;

/*QUERY 6*/
SELECT P.PHONERATETYPE, T.DATEMONTH, SUM(F.PRICE) AS TotaleEntrate,
    100*SUM(F.PRICE)/N1.Totale1 AS PercEntrateTotaleTariffe,
    100*SUM(F.PRICE)/N2.Totale2 AS PercEntrateTotaleMesi
FROM PHONERATE P, FACTS F, TIMEDIM T, (
    SELECT T1.DATEMONTH, SUM(F1.PRICE) AS Totale1
    FROM FACTS F1, TIMEDIM T1
    WHERE F1.ID_TIME = T1.ID_TIME
	GROUP BY T1.DATEMONTH
) N1, (
    SELECT P2.PHONERATETYPE, SUM(F2.PRICE) AS Totale2
    FROM PHONERATE P2, FACTS F2
    WHERE F2.ID_PHONERATE = P2.ID_PHONERATE
	GROUP BY P2.PHONERATETYPE
) N2
WHERE F.ID_TIME = T.ID_TIME
    AND F.ID_PHONERATE = P.ID_PHONERATE
    AND N1.DATEMONTH = T.DATEMONTH
    AND N2.PHONERATETYPE = P.PHONERATETYPE
GROUP BY P.PHONERATETYPE, T.DATEMONTH, N1.Totale1, N2.Totale2
ORDER BY T.DATEMONTH;

/*QUERY 7*/
SELECT REGION, DATEMONTH, DATEYEAR, SUM(NUMBEROFCALLS) AS NumMensileChiamate,
    SUM(SUM(NUMBEROFCALLS)) OVER(PARTITION BY DATEYEAR, REGION
    ORDER BY DATEYEAR, DATEMONTH)
FROM LOCATION L, FACTS F, TIMEDIM T
WHERE L.ID_LOCATION = F.ID_LOCATION_CALLER
    AND T.ID_TIME = F.ID_TIME
GROUP BY REGION, DATEMONTH, DATEYEAR;

/*QUERY 8*/
SELECT DATEMONTH, PHONERATETYPE, L1.REGION AS REGION_CALLER,
    L2.REGION AS REGION_RECEIVER,
    SUM(SUM(PRICE)) OVER(PARTITION BY DATEMONTH) AS RedditoMensile,
    SUM(SUM(PRICE)) OVER (PARTITION BY DATEMONTH, PHONERATETYPE, L1.REGION) AS RedditoMensileChiamante,
    SUM(SUM(PRICE)) OVER (PARTITION BY DATEMONTH, PHONERATETYPE, L2.REGION) AS RedditoMensileDestinatario
FROM FACTS F, TIMEDIM T, PHONERATE P, LOCATION L1, LOCATION L2 --questo per fare in
    -- modo di avere 2 tabelle (L1 = chiamante; L2 = destinatario) e quindi avere
    -- tutto nella stessa query
WHERE L1.ID_LOCATION = F.ID_LOCATION_CALLER
    AND L2.ID_LOCATION = F.ID_LOCATION_RECEIVER
    AND T.ID_TIME = F.ID_TIME
    AND P.ID_PHONERATE = F.ID_PHONERATE
    AND DATEYEAR = '2003'
GROUP BY DATEMONTH, PHONERATETYPE, L1.REGION, L2.REGION
ORDER BY DATEMONTH, PHONERATETYPE, L1.REGION, L2.REGION;